% Produced by CVXGEN, 2020-09-01 12:15:41 -0400.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
v_d = params.v_d;
v_max = params.v_max;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable v;

  minimize(quad_form(v - v_d, eye(1)));
  subject to
    v <= v_max;
cvx_end
vars.v = v;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
